#
# Copyright (C) 2023 RyuujiX <saputradenny712@gmail.com>
# Copyright (C) 2023-2024 Kneba <abenkenary3@gmail.com>
#

name: Compile kernel

env:
   TOKEN: ${{ secrets.TOKEN }}
   USERNAME: ${{ secrets.USERNAME }}
   TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
   TG_TOKEN: ${{ secrets.TG_TOKEN }}

on: [push]

jobs:
  kernel-build:
    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup CI
      run: |
        sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
        sudo pacman -Sy --noconfirm git bc inetutils python3 flex bison libc++ libxml2 python-pipx zip wget cpio jdk-openjdk tzdata && sudo pipx install networkx gupload
    - name: Setup and Build Kernel
      run: bash build.sh
